# Generated by Django 4.1.7 on 2023-03-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name_cult', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name_equip_all', models.CharField(
                    max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdSeria',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name_seria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name_sol', models.CharField(max_length=100)),
                ('prod_ser_sol', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE,
                    to='table.prodseria')),
            ],
        ),
        migrations.CreateModel(
            name='ProdSpec',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name_spec', models.CharField(max_length=100)),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='table.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProdSolutions',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=150, null=True)),
                ('ser_sol', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('solution', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='table.solution')),
            ],
        ),
        migrations.AddField(
            model_name='prodseria',
            name='prod_spec',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='table.prodspec'),
        ),
        migrations.CreateModel(
            name='ProdEquipment',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('firm', models.CharField(max_length=100, null=True)),
                ('types', models.CharField(max_length=100)),
                ('characteristics', models.TextField()),
                ('description', models.TextField()),
                ('name_equip', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='table.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ProdCultivations',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concentration_up_to', models.FloatField()),
                ('concentration_after', models.FloatField()),
                ('viability_up_to', models.FloatField()),
                ('viability_after', models.FloatField()),
                ('ph', models.FloatField(blank=True, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('lactose', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cultivation', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='table.cultivation')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='prod_spec',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='table.prodspec'),
        ),
        migrations.AddField(
            model_name='cultivation',
            name='prod_ser_cult',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE,
                to='table.prodseria'),
        ),
    ]
