# Generated by Django 4.1.7 on 2023-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table',
         '0002_rename_name_cult_cultivation_name_of_cultivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcultivations',
            name='concentration_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcultivations',
            name='concentration_up_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcultivations',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcultivations',
            name='viability_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prodcultivations',
            name='viability_up_to',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
